name: Quality Checks

on:
  workflow_call:
    inputs:
      tox-version:
        required: false
        description: |
          Tox version, which should be used, e.g. `<4`. If not specified, the
          latest version of tox will be installed.
        type: string
        default: ""
      python-version:
        required: false
        description: "Python version (default to 3.10)"
        type: string
        default: "3.10"
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:

  lint-test:
    name: Run lint test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: python3 -m pip install tox${{ inputs.tox-version }}
      - name: Run linters
        run: tox -e lint

  unit-test:
    name: Run unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
      - name: Install dependencies
        run: python3 -m pip install tox${{ inputs.tox-version }}
      - name: Run unit test
        run: tox -e unit

  integration-test:
    needs: [lint-test, unit-test]
    runs-on: ['self-hosted', 'x64', 'jammy', 'xlarge']
    timeout-minutes: 240
    strategy:
      fail-fast: false
      matrix:
        include:
          - juju-channel: "3.4/stable"
            command: "TEST_JUJU3=1 make integration" # using TEST_JUJU3 due to https://github.com/openstack-charmers/zaza/commit/af7eea953dd5d74d3d074fe67b5765dca3911ca6
    steps:
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: canonical/action-tmate@main
        if: ${{ inputs.debug_enabled }}
        with:
          detached: true
      - uses: actions/checkout@v4
      - name: Setup Juju ${{ matrix.juju-channel }} environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: ${{ matrix.juju-channel }}
          bootstrap-options: '--bootstrap-constraints="virt-type=virtual-machine mem=8G"'
      - name: Run functional tests
        run: ${{ matrix.command }}
      - name: Collect juju-crashdump
        if: failure()
        run: juju-crashdump --model "$(juju models | grep 'zaza-' | awk '{print $1}')"
