name: Pull Request

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  workflow_call:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  check-code-quality:
    steps:
      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Setup tmate session
        uses: canonical/action-tmate@main
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true
      - name: Run charm code quality checks
        uses: ./.github/workflows/_quality_check.yaml
        secrets: inherit
        with:
          tox-version: ""
          python-version: "3.10"

  check-file-updates:
    name: Check updates for charm files
    uses: ./.github/workflows/_check_file_update.yaml
